### ISSUE TITLE
Current version not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [opacapp/opacclient#641] opened 2021-07-28 05:57 UTC
Dear team,

when I take a look on google play store the current version is 6.3.7, in the F-Droid store the current version is 6.3.8.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by johan12345** [comment] 2021-07-28 06:04
Duplicate of #615. Should be fixed with the next release.

**Closed by johan12345** 2021-07-28 06:04 UTC
